# Generated by Django 5.2.6 on 2025-09-16 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('master_categories', models.ManyToManyField(related_name='groups', to='app.mastercategory')),
            ],
        ),
        migrations.CreateModel(
            name='MasterNewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('post_image', models.ImageField(upload_to='recon/posts/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_news_posts', to=settings.AUTH_USER_MODEL)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_news_posts', to='app.mastercategory')),
            ],
        ),
        migrations.CreateModel(
            name='PortalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('external_id', models.CharField(max_length=100)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.portal')),
            ],
            options={
                'unique_together': {('portal', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('ai_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('ai_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('Head_Lines', models.BooleanField(blank=True, null=True)),
                ('articles', models.BooleanField(blank=True, null=True)),
                ('trending', models.BooleanField(blank=True, null=True)),
                ('BreakingNews', models.BooleanField(blank=True, null=True)),
                ('Event', models.BooleanField(blank=True, null=True)),
                ('Event_date', models.DateField(blank=True, null=True)),
                ('Eventend_date', models.DateField(blank=True, null=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('post_tag', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_distribution', to='app.masternewspost')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portal')),
                ('portal_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.portalcategory')),
            ],
            options={
                'unique_together': {('news_post', 'portal')},
            },
        ),
        migrations.CreateModel(
            name='MasterCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='app.mastercategory')),
                ('portal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='app.portalcategory')),
            ],
            options={
                'unique_together': {('master_category', 'portal_category')},
            },
        ),
    ]
