# Generated by Django 5.2.6 on 2025-09-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group_created_at_group_inactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternewspost',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_news_posts', to='app.group'),
        ),
        migrations.AddField(
            model_name='newsdistribution',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_distributions', to='app.group'),
        ),
        migrations.AddField(
            model_name='newsdistribution',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_distributions', to='app.mastercategory'),
        ),
        migrations.CreateModel(
            name='PortalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt', to='app.portal')),
            ],
        ),
    ]
