# Generated by Django 5.2.6 on 2025-09-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_masternewspost_group_newsdistribution_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masternewspost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='masternewspost',
            name='master_category',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='BreakingNews',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='Event',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='Event_date',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='Eventend_date',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='Head_Lines',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='post_tag',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='newsdistribution',
            name='trending',
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='BreakingNews',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='Event',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='Event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='Eventend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='Head_Lines',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='articles',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='post_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='trending',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masternewspost',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsdistribution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
