# Generated by Django 5.2.6 on 2025-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_masternewspost_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masternewspost',
            old_name='Eventend_date',
            new_name='Event_end_date',
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='breaking_news',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='counter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
