# Generated by Django 5.2.6 on 2025-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_eventend_date_masternewspost_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdistribution',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
