# Generated by Django 5.2.6 on 2025-09-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newsdistribution_retry_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masternewspost',
            name='breaking_news',
        ),
        migrations.AlterField(
            model_name='masternewspost',
            name='post_image',
            field=models.ImageField(upload_to='media/posts/%Y/%m/%d/'),
        ),
    ]
