# Generated by Django 5.2.6 on 2025-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_masternewspost_breaking_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternewspost',
            name='latest_news',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='upcoming_event',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
