# Generated by Django 5.2.6 on 2025-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_masternewspost_latest_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masternewspost',
            name='post_image',
            field=models.ImageField(upload_to='posts/%Y/%m/%d/'),
        ),
    ]
