# Generated by Django 5.2.6 on 2025-09-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_masternewspost_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategorymapping',
            name='use_default_content',
            field=models.BooleanField(default=False, help_text='If true, send MasterNewsPost content without GPT rewrite'),
        ),
    ]
