# Generated by Django 5.2.6 on 2025-09-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mastercategorymapping_use_default_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternewspost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
