# Generated by Django 5.2.6 on 2025-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_masternewspost_meta_title_masternewspost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdistribution',
            name='ai_meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsdistribution',
            name='ai_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
