# Generated by Django 5.2.6 on 2025-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_newsdistribution_ai_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdistribution',
            name='portal_news_id',
            field=models.CharField(blank=True, help_text='ID of the NewsPost object in the target portal.', max_length=255, null=True),
        ),
    ]
