# Generated by Django 5.2.6 on 2025-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_newsdistribution_portal_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcategory',
            name='parent_external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portalcategory',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
