# Generated by Django 5.2.6 on 2025-10-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_portalcategory_parent_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='domain_url',
            field=models.URLField(help_text='Just the domain url ex: https://domain.com', null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='base_url',
            field=models.URLField(help_text="API's Base url ex: https://domain.com/portal_name"),
        ),
    ]
