# Generated by Django 5.2.6 on 2025-10-11 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_portal_domain_url_alter_portal_base_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalprompt',
            options={'verbose_name': 'Portal Prompt', 'verbose_name_plural': 'Portal Prompts'},
        ),
        migrations.AddField(
            model_name='portalprompt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portalprompt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portalprompt',
            name='is_global_prompt',
            field=models.BooleanField(default=False, help_text='If true, this prompt applies globally when no portal-specific prompt exists.'),
        ),
        migrations.AddField(
            model_name='portalprompt',
            name='name',
            field=models.CharField(help_text="Prompt name, e.g., 'Default Rewrite Prompt'", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='portal',
            name='base_url',
            field=models.URLField(help_text="API's url ex: https://domain.com/portal_name"),
        ),
        migrations.AlterField(
            model_name='portalprompt',
            name='portal',
            field=models.OneToOneField(blank=True, help_text='Optional — if empty, use this prompt globally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt', to='app.portal'),
        ),
        migrations.AlterField(
            model_name='portalprompt',
            name='prompt_text',
            field=models.TextField(help_text='The text prompt that controls GPT rewriting behavior.'),
        ),
    ]
