# Generated by Django 5.2.6 on 2025-10-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_portalprompt_options_portalprompt_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategorymapping',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
