# Generated by Django 5.2.6 on 2025-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mastercategorymapping_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternewspost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=20),
        ),
    ]
