# Generated by Django 5.2.6 on 2025-10-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_masternewspost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternewspost',
            name='excluded_portals',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='app.mastercategory'),
        ),
    ]
