# Generated by Django 5.2.6 on 2025-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_masternewspost_excluded_portals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdistribution',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsdistribution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsdistribution',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Time taken in seconds to publish on this portal'),
        ),
    ]
