# Generated by Django 5.2.6 on 2025-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_newsdistribution_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternewspost',
            name='exclude_portal_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='portal_category_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
