# Generated by Django 5.2.6 on 2025-11-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_masternewspost_exclude_portal_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdistribution',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
