# Generated by Django 5.2.6 on 2025-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_newsdistribution_edit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdistribution',
            name='edited_image',
            field=models.ImageField(blank=True, help_text='Edited image for this portal-specific distribution.', null=True, upload_to='distribution_edits/%Y/%m/%d/'),
        ),
    ]
