# Generated by Django 5.2.6 on 2025-11-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_newssource_newssourcefeed_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
