# Generated by Django 5.2.6 on 2025-11-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_newsarticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternewspost',
            name='cross_portal_category_id',
            field=models.IntegerField(blank=True, help_text='The specific portal category that triggers cross-posting logic.', null=True),
        ),
        migrations.CreateModel(
            name='CrossPortalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('source_category', models.ForeignKey(help_text=' The category the user selects (Trigger)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_mappings', to='app.portalcategory')),
                ('target_category', models.ForeignKey(help_text='The category to automatically distribute to', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mappings', to='app.portalcategory')),
            ],
            options={
                'verbose_name': 'Cross Portal Mapping',
                'verbose_name_plural': 'Cross Portal Mappings',
                'unique_together': {('source_category', 'target_category')},
            },
        ),
    ]
