# Generated by Django 5.2.6 on 2025-12-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_masternewspost_cross_portal_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterNewsPortalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_image', models.ImageField(upload_to='portal_specific/%Y/%m/%d/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_images', to='app.masternewspost')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_post_images', to='app.portal')),
            ],
            options={
                'unique_together': {('news_post', 'portal')},
            },
        ),
    ]
