# Generated by Django 5.2.6 on 2025-12-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_masternewsportalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newssource',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newssourcefeed',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newssourcefeed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newssourcefeed',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
