# Generated by Django 5.2.4 on 2025-12-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_newsarticle_distributed_newsarticle_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='distributed',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='country',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='language',
        ),
        migrations.RemoveField(
            model_name='newssourcefeed',
            name='country',
        ),
        migrations.RemoveField(
            model_name='newssourcefeed',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newssourcefeed',
            name='language',
        ),
        migrations.AddField(
            model_name='masternewspost',
            name='newstype_slug',
            field=models.SlugField(blank=True, help_text="Slug for newsfrom field (e.g., 'punjab', 'warraich-towns')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsdistribution',
            name='newstype_slug_sent',
            field=models.SlugField(blank=True, help_text='The newstype slug sent to portal', max_length=100, null=True),
        ),
    ]
