# Generated by Django 5.2.6 on 2025-09-17 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_group_created_at_group_inactivated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('portal_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('portal_username', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('PENDING', 'Pending'), ('MISMATCH', 'Mismatch')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='app.portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_user_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'portal')},
            },
        ),
    ]
