# Generated by Django 5.2.6 on 2025-09-18 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group_created_at_group_inactivated_at_and_more'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='app.group')),
                ('master_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='app.mastercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_group_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('master_category__isnull', True)), models.Q(('group__isnull', True), ('master_category__isnull', False)), _connector='OR'), name='only_one_of_group_or_category'), models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group_assignment'), models.UniqueConstraint(fields=('user', 'master_category'), name='unique_user_category_assignment')],
            },
        ),
    ]
